### ISSUE TITLE
Won't compile with HDF5 1.12 (with proposed fix).

### ISSUE THREAD

**Issue by doctorcbpower** [ICRAR/VELOCIraptor-STF#42]
This is an issue on my MacBook pro after upgrading to HDF5 1.12. The compiler is clang12. It appears that an additional parameter is now required by `H5Oget_info` and `H5Oget_info_by_name`.

After the most basic invocation of cmake (to make sure the code compiled after updating a number of libraries), I ran make and hit the following error;

> [ 45%] Building CXX object src/CMakeFiles/velociraptor.dir/hdfio.cxx.o
> In file included from /Users/cpower/Codes/VELOCIraptor-STF/src/hdfio.cxx:28:
> /Users/cpower/Codes/VELOCIraptor-STF/src/hdfitems.h:161:9: error: no matching
>       function for call to 'H5Oget_info_by_name3'
>         H5Oget_info_by_name(ids.back(), parts[0].c_str(), &object_info, ...
>         ^~~~~~~~~~~~~~~~~~~
> /usr/local/Cellar/hdf5/1.12.0_1/include/H5version.h:772:31: note: expanded from
>       macro 'H5Oget_info_by_name'
>   #define H5Oget_info_by_name H5Oget_info_by_name3
>                               ^~~~~~~~~~~~~~~~~~~~
> /usr/local/Cellar/hdf5/1.12.0_1/include/H5Opublic.h:188:15: note: candidate
>       function not viable: requires 5 arguments, but 4 were provided
> H5_DLL herr_t H5Oget_info_by_name3(hid_t loc_id, const char *name, H5O_i...
> 

I fixed this by updating the instances in `hdfitems.h` - namely, at `line 161`, changing

`H5Oget_info_by_name(ids.back(), parts[0].c_str(), &object_info, H5P_DEFAULT);
`
to 

`H5Oget_info_by_name(ids.back(), parts[0].c_str(), &object_info, H5O_INFO_ALL, H5P_DEFAULT);`

and at `line 203`, changing 

`H5Oget_info(id, &object_info);`

to 

`H5Oget_info(id, &object_info,H5O_INFO_ALL);`

I used the following to identify the appropriate fixes;
[https://portal.hdfgroup.org/display/HDF5/H5O_GET_INFO_BY_NAME3](url)
[https://portal.hdfgroup.org/display/HDF5/H5O_GET_INFO3](url)

This hasn't affected versions of VR running on e.g. NCI Gadi - there the version of HDF5 is still 1.10.

**Comment by rtobar** [comment]
@doctorcbpower thanks for the information. And yes, the fix looks right. There was a fix in pelahi@72f90bf, but it contains other changes I'd avoid bringing, plus it doesn't correctly invoke `H5Oget_info`. So instead of simply cherry picking it I'll be more manually patching this.

**Comment by rtobar** [comment]
Fix now present on the `master` branch.

**Comment by doctorcbpower** [comment]
Great, thanks for sorting this out, Rodrigo.
